version: '3.4'
services:
  truffle:
    build: .
    command: truffle develop
    volumes:
      - ./build:/app/build
      - ./contracts:/app/contracts
      - ./migrations:/app/migrations
    tty: true
    stdin_open: true
    ports:
      - "9545:9545"

  eth-bridge:
    image: marketproject/ethereum-bridge:0.5.6
    command: -H truffle:9545 -a 9 --dev
    restart: unless-stopped
    depends_on:
      - truffle
    links:
      - truffle

  app:
    build: .
    volumes:
      - ./build:/app/build
      - ./config:/app/config
      - ./public:/app/public
      - ./src:/app/src
      - ./test:/app/test
    ports:
      - "3000:3000"
    depends_on:
      - truffle
